# Generated by Django 5.2.3 on 2026-01-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0002_remove_products_createdat_products_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
    ]
