# Generated by Django 6.0.1 on 2026-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0004_alter_cartitems_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
