# Generated by Django 6.0.1 on 2026-02-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0005_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together=set(),
        ),
    ]
