# Generated by Django 6.0.1 on 2026-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0006_alter_cartitems_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
