# Generated by Django 6.0.1 on 2026-02-06 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0009_rename_price_orderitems_price_at_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('user', 'product')},
        ),
    ]
