# Generated by Django 6.0.1 on 2026-02-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0010_alter_cartitems_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='price_at_time',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecomproject.order'),
        ),
    ]
