# Generated by Django 6.0.1 on 2026-02-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0011_rename_price_at_time_orderitems_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='price',
            new_name='price_at_time',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomproject.order'),
        ),
    ]
