# Generated by Django 6.0.1 on 2026-03-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0018_alter_order_status_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='cateoryimage',
        ),
        migrations.AddField(
            model_name='products',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
