# Generated by Django 6.0.1 on 2026-03-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0019_rename_image_products_cateoryimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cateoryimage',
            new_name='categoryimage',
        ),
    ]
