# Generated by Django 6.0.1 on 2026-03-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0020_rename_cateoryimage_products_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productimage',
            new_name='image',
        ),
    ]
