# Generated by Django 6.0.1 on 2026-03-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0021_rename_productimage_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categoryimage',
        ),
    ]
