# Generated by Django 6.0.1 on 2026-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0022_remove_products_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoryimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
