# Generated by Django 6.0.1 on 2026-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0023_products_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='categoryimage',
        ),
    ]
