# Generated by Django 6.0.1 on 2026-07-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproject', '0026_alter_emailotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
